export const ADD_NEW_DEAL = "ADD_NEW_DEAL";
export const CHANGE_MOTIVE_STATUS = "CHANGE_MOTIVE_STATUS";
export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_DEAL = 'UPDATE_DEAL';
export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_DEAL = "DELETE_DEAL";

export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
export const ADD_NEW_IDEA = "ADD_NEW_IDEA";
export const CHANGE_RESULT_OF_THE_IDEA = "CHANGE_RESULT_OF_THE_IDEA";
export const DELETE_IDEA = 'DELETE_IDEA';
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_IDEAS_FOR_CATEGORY = 'DELETE_IDEAS_FOR_CATEGORY';